name: Xcode - Build IPA

on:
  push:
    branches: [ "noWaterMark" ]
  pull_request:
    branches: [ "noWaterMark" ]

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: "git submodule update --init --recursive"
      - name: Build
        run: |
          xcodebuild -verbose -scheme Moonlight-ZWM -sdk iphoneos -configuration AppStoreDistribution  archive -archivePath $PWD/build/Moonlight.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
          mkdir -p ./build/IPA && mkdir -p ./build/IPA/Payload
          cp -r ./build/Moonlight.xcarchive/Products/Applications/Moonlight-ZWM.app ./build/IPA/Payload/Moonlight-ZWM.app
          cd ./build/IPA && zip -r ../../build/Moonlight.ipa ./Payload/* && cd ../..
      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moonlight.ipa
          path: build/Moonlight.ipa
